name: Prometheus_Puzzles
on:
  push:
    env:
      dbpass: ${{ secrets.DBPass }}
      dbName: ${{ secrets.DBName }}
      dbDatabase: ${{ secrets.DBDatabase }}
      dbUsername: ${{ secrets.DBUserName }}
